SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT FNAME, JOBID, SALARY, COMM_PCT FROM EMPLOYEES;

SELECT FNAME, JOBID, SALARY, COMM_PCT, SALARY + SALARY * COMM_PCT FROM EMPLOYEES;
SELECT FNAME, JOBID, SALARY, COMM_PCT, SALARY * COMM_PCT FROM EMPLOYEES;
SELECT FNAME, JOBID, SALARY, COMM_PCT, SALARY + SALARY * NVL(COMM_PCT, 0) FROM EMPLOYEES;
SELECT FNAME, JOBID, SALARY, COMM_PCT, SALARY + SALARY * NVL(COMM_PCT, 0) AS TOTAL_INCOME FROM EMPLOYEES;
SELECT FNAME FIRST_NAME, JOBID, SALARY, COMM_PCT, SALARY + SALARY * NVL(COMM_PCT, 0) AS TOTAL_INCOME FROM EMPLOYEES;
SELECT FNAME "FIRST NAME", JOBID, SALARY, COMM_PCT, SALARY + SALARY * NVL(COMM_PCT, 0) AS TOTAL_INCOME FROM EMPLOYEES;
SELECT FNAME || ' IS ' || JOBID || ' AND GETS ' || SALARY FROM EMPLOYEES;
SELECT FNAME || ' IS ' || JOBID || ' AND GETS ' || SALARY AS "EMP. DETAILS" FROM EMPLOYEES;
SELECT JOBID FROM EMPLOYEES;
SELECT DISTINCT JOBID FROM EMPLOYEES;
SELECT DISTINCT DEPT_ID FROM EMPLOYEES;
SELECT DISTINCT JOBID, DEPT_ID FROM EMPLOYEES;

SELECT * FROM EMPLOYEES WHERE SALARY > 10000;

SELECT * FROM EMPLOYEES WHERE JOBID = 'IT_PROG';

-- who joined after 1st june 1999

SELECT * FROM EMPLOYEES WHERE HIREDATE > '01-06-1999';

SELECT * FROM EMPLOYEES WHERE HIREDATE > '01-JUN-1999';

SELECT * FROM EMPLOYEES WHERE HIREDATE > '06-01-1999';

SELECT * FROM EMPLOYEES WHERE HIREDATE > '1999-06-01';

SELECT * FROM EMPLOYEES WHERE HIREDATE > TO_DATE('1999-06-01', 'YYYY-MM-DD');

SELECT * FROM EMPLOYEES WHERE JOBID = 'ST_CLERK' OR JOBID = 'SA_MAN' AND SALARY > 4000;

SELECT * FROM EMPLOYEES WHERE JOBID in ('ST_CLERK', 'SA_MAN') AND SALARY > 4000;

SELECT * FROM EMPLOYEES WHERE SALARY BETWEEN 10000 AND 20000;

SELECT * FROM EMPLOYEES WHERE SALARY BETWEEN 20000 AND 10000;
 
-- those who joined in the yar 1999

SELECT * FROM EMPLOYEES WHERE HIREDATE BETWEEN '01-JAN-1999' AND '31-DEC-1999';

SELECT * FROM EMPLOYEES WHERE FNAME LIKE 'S%';

SELECT * FROM EMPLOYEES WHERE FNAME LIKE '%r';

SELECT * FROM EMPLOYEES WHERE FNAME LIKE '%e_';

SELECT * FROM EMPLOYEES WHERE LOWER(FNAME) LIKE '%l%';

SELECT * FROM EMPLOYEES WHERE FNAME LIKE '%l%' OR FNAME LIKE '%L%';

SELECT * FROM EMPLOYEES WHERE FNAME LIKE '%*%%' ESCAPE '*';

SELECT * FROM EMPLOYEES WHERE FNAME LIKE '____';

SELECT * FROM EMPLOYEES WHERE LENGTH(FNAME) = 4;

-- those who joined in the year 1999

SELECT * FROM EMPLOYEES WHERE HIREDATE LIKE '%99';

SELECT * FROM EMPLOYEES WHERE COMM_PCT = NULL;

SELECT * FROM EMPLOYEES WHERE COMM_PCT IS NULL;

SELECT * FROM EMPLOYEES WHERE COMM_PCT IS NOT NULL;

SELECT * FROM EMPLOYEES;

SELECT ROWID, FNAME, JOBID, SALARY FROM EMPLOYEES;

SELECT FNAME, JOBID, SALARY FROM EMPLOYEES ORDER BY FNAME;

SELECT FNAME, JOBID, SALARY FROM EMPLOYEES ORDER BY FNAME DESC;

SELECT FNAME, JOBID, SALARY FROM EMPLOYEES
  WHERE SALARY > 5000
  ORDER BY JOBID, SALARY DESC, FNAME ;
  
SELECT FNAME, JOBID, SALARY, COMM_PCT, SALARY + SALARY * NVL(COMM_PCT, 0) AS TOTAL_INCOME 
   FROM EMPLOYEES
   WHERE TOTAL_INCOME > 15000
   ORDER BY TOTAL_INCOME;

SELECT FNAME, JOBID, SALARY, COMM_PCT, SALARY + SALARY * NVL(COMM_PCT, 0) AS TOTAL_INCOME 
   FROM EMPLOYEES
  ORDER BY 5;
   
SELECT FNAME, JOBID, SALARY, COMM_PCT, SALARY + SALARY * NVL(COMM_PCT, 0) AS TOTAL_INCOME 
   FROM EMPLOYEES
  ORDER BY 5;
   
   
   
