SELECT ENAME, COMM FROM EMP;
SELECT SUM(COMM) FROM EMP;
SELECT AVG(COMM), SUM(COMM)/COUNT(EMPNO) FROM EMP;
SELECT AVG(COMM), ROUND(SUM(COMM)/COUNT(COMM)) FROM EMP;
SELECT AVG(COMM), ROUND(SUM(COMM)/COUNT(EMPNO)) FROM EMP;
SELECT AVG(NVL(COMM, 0)), ROUND(SUM(COMM)/COUNT(EMPNO)) FROM EMP;
SELECT ROUND(AVG(NVL(COMM, 0))), ROUND(SUM(COMM)/COUNT(EMPNO)) FROM EMP;
SELECT COUNT(EMPNO), SUM(SAL) FROM EMP
  GROUP BY DEPTNO;
SELECT DEPTNO, COUNT(EMPNO), SUM(SAL) FROM EMP
  GROUP BY DEPTNO;
SELECT JOB, COUNT(EMPNO), SUM(SAL) FROM EMP
  GROUP BY JOB;
SELECT JOB, COUNT(EMPNO), SUM(SAL) 
  FROM EMP
  HAVING COUNT(EMPNO) > 2
  GROUP BY JOB;
SELECT JOB, COUNT(EMPNO), SUM(SAL) 
  FROM EMP
  GROUP BY JOB
  HAVING COUNT(EMPNO) > 2
SELECT JOB, DEPTNO, COUNT(EMPNO), SUM(SAL) FROM EMP
  GROUP BY JOB, DEPTNO;
SELECT  MAX(SAL) FROM EMP;
SELECT MAX(SAL) FROM EMP;
SELECT MAX(SAL) FROM EMP
SELECT * FROM EMP WHERE SAL = (SELECT MAX(SAL) FROM EMP);
SELECT EXTRACT (YEAR FROM HIREDATE ) "YEAR", COUNT(*) "NO OF EMPS."    
  FROM EMP
  GROUP BY EXTRACT(YEAR FROM HIREDATE);
SELECT TO_CHAR(HIREDATE, 'YYYY') "YEAR", COUNT(*) "NO OF EMPS."    
  FROM EMP
  GROUP BY TO_CHAR(HIREDATE, 'YYYY');



SELECT TO_CHAR(HIREDATE, 'YYYY') "YEAR", COUNT(*) "NO OF EMPS."    
  FROM EMP
  GROUP BY TO_CHAR(HIREDATE, 'YYYY');
