SELECT INITCAP('HELLO how aRE yOu?') FROM DUAL;

SELECT 45345 * 343 FROM DUAL;

SELECT FNAME || ' IS ' || JOBID || ' AND GETS ' || SALARY FROM EMPLOYEES;

SELECT CONCAT(FNAME, CONCAT(' IS ', CONCAT(JOBID, CONCAT(' AND GETS ', SALARY)))) FROM EMPLOYEES;

--Listing those whose name starts with A

SELECT FNAME FROM EMPLOYEES WHERE SUBSTR(FNAME, 1, 1) = 'A';

-- List those whose name containts %

SELECT FNAME FROM EMPLOYEES WHERE INSTR(FNAME , '%') > 0;

CREATE TABLE T1(FULLNAME VARCHAR2(20));

INSERT INTO T1 VALUES('DIPALI SHAH');
INSERT INTO T1 VALUES('KALYANI GOSAVI');
INSERT INTO T1 VALUES('DRISTI SASE');

SELECT * FROM T1;

-- FULLNAME   FIRST NAME    LAST NAME

SELECT FULLNAME, SUBSTR(FULLNAME, 1, INSTR(FULLNAME, ' ') - 1) "FIRST NAME",
                 SUBSTR(FULLNAME, INSTR(FULLNAME, ' ')+1) "LAST NAME" FROM T1;
                 
SELECT TRIM('        HELLO             ') TRIM_EG FROM DUAL;

SELECT TRIM(LEADING ' ' FROM '        HELLO             ') TRIM_EG FROM DUAL;

SELECT TRIM('H' FROM 'HHHHHHHHELLOHHHHHHHHH') FROM DUAL;

SELECT TRIM(TRAILING 'H' FROM 'HHHHHHHHELLOHHHHHHHHH') FROM DUAL;

SELECT LPAD(FNAME, LENGTH(FNAME) + 5, '*') FROM EMPLOYEES;

SELECT RPAD(LPAD(FNAME, LENGTH(FNAME) + 5, '*'), LENGTH(FNAME) + 10, '*' ) FROM EMPLOYEES;

SELECT SOUNDEX('DIPALI'), SOUNDEX('DEEPALI') FROM DUAL;

SELECT * FROM EMPLOYEES WHERE FNAME = 'Stiven';

SELECT * FROM EMPLOYEES WHERE SOUNDEX(FNAME) = SOUNDEX('Stiven');

SELECT REPLACE('DIPALI', 'I', 'EE') FROM DUAL;

SELECT REPLACE('DIPALI', 'IP', 'EX') FROM DUAL;

SELECT SYSDATE FROM DUAL;

-- 13TH OF OCTOBER, 2023 04:53:23 PM

SELECT TO_CHAR(SYSDATE, 'DDTH "OF" MONTH, YYYY HH:MI:SS AM') FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'FMDAY, DDTH "OF" MONTH, YYYY HH:MI:SS ') FROM DUAL;

-- List those who joined in the year 1999

SELECT FNAME, HIREDATE FROM EMPLOYEES WHERE TO_CHAR(HIREDATE, 'YYYY') = '1999';

SELECT FNAME, HIREDATE FROM EMPLOYEES WHERE TO_CHAR(HIREDATE, 'DD') < 15;

SELECT SYSDATE + 30 FROM DUAL;

SELECT SYSDATE - 30 FROM DUAL;

SELECT '14-MAY-2023' + 17 FROM DUAL;

SELECT 'ABC' + 10 FROM DUAL;

SELECT TO_DATE('14-MAY-2023') + 17 FROM DUAL;

SELECT FNAME, HIREDATE, (SYSDATE - HIREDATE) / 30 "NO OF DAYS" FROM EMPLOYEES;

SELECT NEXT_DAY(SYSDATE, 'TUESDAY') FROM DUAL;
SELECT NEXT_DAY(SYSDATE, 'TUE') FROM DUAL;
SELECT NEXT_DAY(SYSDATE, 3) FROM DUAL;

SELECT FNAME, SALARY FROM EMPLOYEES;

SELECT FNAME, SALARY, TO_CHAR(SALARY, 'L09,999.99') FROM EMPLOYEES;

SELECT TO_NUMBER(PHONE_NO) FROM EMPLOYEES;

SELECT TO_NUMBER('12345') FROM DUAL;

SELECT TO_NUMBER('ABC') FROM DUAL;

SELECT USER FROM DUAL;

SHOW USER

/*DECODE( <arg1>, <arg2>, <arg3>,
               <arg4>, <arg5>,
                   ...
	 	<argN>, <argN+1>
		[,<default val.>])
arg1 = arg2

SA_MAN 	20%
IT_PROG	10%
ST_CLERK		5%
Others		1% */

SELECT FNAME, JOBID, SALARY, DECODE(JOBID, 'SA_MAN', SALARY * .2,
                                            'IT_PROG', SALARY * .1,
                                            'ST_CLERK', SALARY * .05,
                                            SALARY * .01) INCENTIVES
  FROM EMPLOYEES;        
  
/*
CASE Expression
---------------
CASE WHEN <cond.1> THEN <ret.val.1>
     WHEN <cond.2> THEN <ret.val.2>
	...
     WHEN <cond.N> THEN <ret.val.N>
  [ELSE <deffault val.>]
END */

SELECT FNAME, JOBID, SALARY, CASE WHEN JOBID = 'SA_MAN' THEN SALARY * .2
                                  WHEN JOBID = 'IT_PROG' THEN SALARY * .1
                                  WHEN JOBID = 'ST_CLERK' THEN SALARY * .05
                              ELSE SALARY * .01
                             END AS INCENTIVES
  FROM EMPLOYEES;                             











