/* STUDENT
   -------
   S_RNO (PK)
   S_NAME (NN)
   S_MOB (UNIQUE) */
   
CREATE TABLE STUDENT(S_RNO CHAR(5) CONSTRAINT STUDENT_S_RNO_PK PRIMARY KEY,
                     S_NAME VARCHAR2(20) CONSTRAINT STUDENT_S_NAME_NN NOT NULL,
                     S_MOBILE VARCHAR2(50) CONSTRAINT STUDENT_S_MOBILE_UNQ UNIQUE);   

/* COURSE
   ------
   C_ID (PK)
   C_DESC (NN)
   C_DUR ( >0 ) */
   
CREATE TABLE COURSE(C_ID INT CONSTRAINT COURSE_C_ID_PK PRIMARY KEY,
                    C_DESC VARCHAR2(20) CONSTRAINT COURSE_C_DESC_NN NOT NULL,
                    C_DUR INT CHECK(C_DUR > 0));   

/* STUD_COURSE  PK(S_RNO, C_ID)
   -----------
   S_RNO (FK --> STUDENT(S_RNO))
   C_ID  (FK --> COURSE(C_ID))
   ST_DATE
   END_DATE ( > ST_DATE) */
   
CREATE TABLE STUD_COURSE(S_RNO CHAR(5) CONSTRAINT STUD_COURSE_S_RNO_FK REFERENCES STUDENT(S_RNO),
                         C_ID INT, ST_DATE DATE,
                         END_DATE DATE ,
                         CONSTRAINT STUD_COURSE_C_ID_FK FOREIGN KEY(C_ID) REFERENCES COURSE(C_ID),
                         CONSTRAINT STUD_COURSE_S_RNO_C_ID_PK PRIMARY KEY(S_RNO, C_ID),
                         CONSTRAINT STUD_COURSE_END_DATE_CHQ CHECK(END_DATE > ST_DATE));   
   
                    