SELECT * FROM EMP WHERE SAL = (SELECT MAX(SAL) FROM EMP);

SELECT * FROM EMP ORDER BY SAL DESC
  OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY;
  
-- Getting 2nd max

SELECT MAX(SAL) FROM EMP WHERE SAL < (SELECT MAX(SAL) FROM EMP);

SELECT * FROM EMP ORDER BY SAL DESC
  OFFSET 1 ROWS FETCH NEXT 1 ROWS ONLY;
  
-- Getting 3rd max

SELECT MAX(SAL) FROM EMP WHERE SAL < (SELECT MAX(SAL) FROM EMP WHERE SAL < (SELECT MAX(SAL) FROM EMP));
  
SELECT * FROM EMP ORDER BY SAL DESC
  OFFSET 2 ROWS FETCH NEXT 1 ROWS ONLY;
  
SELECT * FROM EMP 
  WHERE SAL = (SELECT DISTINCT SAL FROM EMP ORDER BY SAL DESC OFFSET 2 ROWS FETCH NEXT 1 ROWS ONLY);
  
-- List those who work in the same dept as of MARTIN

SELECT * FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'MARTIN');

SELECT E.ENAME, E.DEPTNO 
  FROM EMP E JOIN EMP D ON(E.DEPTNO = D.DEPTNO)
  WHERE D.ENAME = 'MARTIN' AND E.ENAME <> 'MARTIN';
  
SELECT DEPTNO, SUM(SAL) FROM EMP WHERE DEPTNO IS NOT NULL GROUP BY DEPTNO;  

-- List only those departments, whose total salary is maximum amongst all.

SELECT DEPTNO, SUM(SAL) FROM EMP WHERE DEPTNO IS NOT NULL GROUP BY DEPTNO ORDER BY SUM(SAL) DESC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY;  

SELECT DEPTNO, SUM(SAL) FROM EMP WHERE DEPTNO IS NOT NULL 
   GROUP BY DEPTNO
   HAVING SUM(SAL) = (SELECT MAX(SUM(SAL)) FROM EMP WHERE DEPTNO IS NOT NULL GROUP BY DEPTNO);

SELECT * FROM EMP WHERE SAL > (SELECT SAL FROM EMP WHERE JOB = 'CLERK');
   
-- List those who get more then any of CLERKs
-- WHERE SAL > 800, 1100, 950, 1300 -- WRONG

  SELECT * FROM EMP WHERE SAL > 800 OR SAL > 1100 OR SAL > 950 OR SAL > 1300;
  
  SELECT * FROM EMP WHERE SAL > (SELECT MIN(SAL) FROM EMP WHERE JOB = 'CLERK');

  SELECT * FROM EMP WHERE SAL >ANY(SELECT SAL FROM EMP WHERE JOB = 'CLERK');

-- List those who get more then all the CLERKs

-- List those who get more than the avg of their own dept

SELECT ENAME, DEPTNO, SAL FROM EMP 
  WHERE SAL > (SELECT AVG(SAL) FROM EMP1 WHERE DEPTNO = EMP.DEPTNO);
  






  
  
  
  